version: 2
submodules:
  include: all
build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
sphinx:
  fail_on_warning: true # do not change or you will be fired
  configuration: docs/source/conf.py
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - sphinx-markdown-tables
    - sphinx_rtd_theme
    - doc
